project:
  type: website
  output-dir: docs
  preview:
    port: 3000
    browser: false

website:
  title: "Nanoroad ANR project"
  description: "Linking NANOstructure and macroscopic properties of bitumen to improve their recyclability and aging: towards a sustainable development of ROAD materials"
  twitter-card: true
  open-graph: true
  reader-mode: true
  page-navigation: true
  repo-branch: main
  repo-url: https://github.com/Nanoroad/website
  # repo-actions: [issue]
  navbar:
    search: true
    right:
      - href: index.qmd
        text: Home
      - href: deliverables.qmd
        text: Deliverables
      - href: biblio.qmd
        text: Bibliography
      - about.qmd

bibliography:
  - _biblio/nanoroad_jfb.bib
suppress-bibliography: false
link-citations: true
csl: _biblio/elsevier-harvard.csl

editor:
    render-on-save: true

format:
  html:
    theme: _config/custom.scss
    css: _config/styles.css
    toc: true
    page-layout: full

execute:
  freeze: auto

